export const ADD_TODO = "ADD_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const EDIT_TODO = "EDIT_TODO";
export const COMPLETE_TODO = "COMPLETE_TODO";
export const COMPLETE_ALL_TODOS = "COMPLETE_ALL_TODOS";
export const CLEAR_ALL = "CLEAR_ALL";
export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";

export const ADD_WARNING = "ADD_WARNING";
export const DELETE_WARNING = "DELETE_WARNING";
export const EDIT_WARNING = "EDIT_WARNING";
export const COMPLETE_WARNING = "COMPLETE_WARNING";
export const COMPLETE_ALL_WARNINGS = "COMPLETE_ALL_WARNINGS";
export const API_CALL_REPORT_REQUEST = "API_CALL_REPORT_REQUEST";
export const API_CALL_REPORT_SUCCESS = "API_CALL_REPORT_SUCCESS";
export const API_CALL_REPORT_FAILURE = "API_CALL_REPORT_FAILURE";
